services:
  aria:
    image: ghcr.io/malvavisc0/aria:latest
    container_name: aria
    hostname: aria
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
