---
name: aria

networks:
  mitty: null

volumes:
  redis: null

services:
  aria:
    image: ghcr.io/malvavisc0/aria:latest
    container_name: aria
    hostname: aria
    restart: always
    env_file:
      - ./.env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    environment:
      TZ: '${TZ}'
      SEARXNG_URL: '${SEARXNG_URL:-http://searxng:8080}'
      BYPARR_URL: '${BYPARR_URL:-http://byparr:8191/v1}'
      BYPARR_TIMEOUT: '${BYPARR_TIMEOUT:-120}'
      AGNO_TELEMETRY: '${AGNO_TELEMETRY:-false}'
      OLLAMA_URL: '${OLLAMA_URL}'
      OLLAMA_MODEL_ID: '${OLLAMA_MODEL_ID}'
      OLLAMA_MODEL_TEMPARATURE: '${OLLAMA_MODEL_TEMPARATURE:-0.65}'
      OLLAMA_MODEL_CONTEXT_LENGTH: '${OLLAMA_MODEL_CONTEXT_LENGTH:-4096}'
      DEBUG_MODE: '${DEBUG_MODE:-false}'
    volumes:
      - './data:/opt/storage'
    networks:
      - mitty
  redis:
    image: 'redis/redis-stack-server:latest'
    container_name: redis
    hostname: redis
    restart: always
    runtime: '${RUNTIME:-runc}'
    expose:
      - '${REDIS_PORT:-6379}'
    environment:
      TZ: '${TZ}'
    volumes:
      - 'redis:/data'
    networks:
      - mitty
  searxng:
    image: 'docker.io/searxng/searxng:latest'
    container_name: searxng
    hostname: searxng
    restart: always
    volumes:
      - './searxng:/etc/searxng'
    environment:
      TZ: '${TZ}'
      SEARXNG_BASE_URL: 'http://${SEARXNG_HOSTNAME:-searxng}:${SEARXNG_PORT:-8080}/'
      SEARXNG_SECRET: '${SEARXNG_SECRET}'
      UWSGI_WORKERS: '${SEARXNG_UWSGI_WORKERS:-4}'
      UWSGI_THREADS: '${SEARXNG_UWSGI_THREADS:-4}'
      SEARXNG_REDIS_URL: 'redis://redis:6379/10'
    expose:
      - '${SEARXNG_PORT:-8080}'
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    networks:
      - mitty
  byparr:
    image: 'ghcr.io/thephaseless/byparr:latest'
    container_name: byparr
    hostname: byparr
    restart: always
    runtime: '${RUNTIME:-runc}'
    environment:
      TZ: '${TZ}'
    expose:
      - '${BYPARR_PORT:-8191}'
    networks:
      - mitty
  dozzle:
    image: 'amir20/dozzle:latest'
    container_name: dozzle
    hostname: dozzle
    ports:
     - 8080:8080
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
    environment:
      - DOZZLE_NO_ANALYTICS=1
      - DOZZLE_HOSTNAME=aria
      - DOZZLE_LEVEL=debug
    networks:
      - mitty
