[project]
name = "aria"
version = "1.0.0"
description = "Aria: FastAPI backend for chat sessions and messages"
authors = [{ name = "Your Name", email = "your.email@example.com" }]
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "fastapi",
    "uvicorn",
    "tortoise-orm",
    "typer",
]

[project.scripts]
aria = "aria.cli:app"

[tool.setuptools.packages.find]
where = ["aria"]
