# Jekyll configuration for Aria GitHub Pages

# Site settings
domain: malvavisc0.github.io 
title: Aria - Your Personal AI Assistant
description: A powerful, self-hosted AI assistant designed for reasoning, task completion, and seamless interaction

# Build settings
markdown: kramdown
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

# Theme customization
show_downloads: true
github:
  repository_url: https://github.com/malvavisc0/aria
  zip_url: https://github.com/malvavisc0/aria/archive/refs/heads/master.zip
  tar_url: https://github.com/malvavisc0/aria/archive/refs/heads/master.tar.gz

# Custom CSS
custom_css: /assets/css/custom.css

# Navigation
navigation:
  - title: Home
    url: /
  - title: Installation
    url: /installation
  - title: Configuration
    url: /configuration
  - title: Usage
    url: /usage
  - title: License
    url: /license
