use_default_settings: true

search:
  formats:
    - html
    - csv
    - json # Required for agents to search

server:
  limiter: false # Disable rate limiting for internal Docker network
  image_proxy: true
